# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml

version: "0.5.6.{build}"

skip_tags: true

# branches:
#   only:
#     - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  matrix:
  # - GOARCH: 386
  #   GOVERSION: 1.5.3
  - GOARCH: amd64
    GOVERSION: 1.5.3

clone_folder: c:\gopath\src\github.com\docker\machine

install:
  - set Path=c:\go\bin;%Path%
  - echo %Path%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - go version
  - go env
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cover
  - go get github.com/tools/godep
  - go get github.com/aktau/github-release

build_script:
  - go test -v ./...
  - go vet ./...
  - git rev-parse HEAD

test: off

deploy: off
