# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml

version: "0.5.6.{build}"

skip_tags: true

# branches:
#   only:
#     - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  # Support go1.5 vendoring (let us avoid messing with GOPATH or using godep)
  GO15VENDOREXPERIMENT: 1
  matrix:
  # - GOARCH: 386
  #   GOVERSION: 1.5.3
  - GOARCH: amd64
    GOVERSION: 1.5.3

clone_folder: c:\gopath\src\github.com\docker\machine

install:
  - set Path=c:\go\bin;%Path%
  - echo %Path%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - go version
  - go env
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cover
  - go get github.com/tools/godep
  - go get github.com/aktau/github-release

build_script:
  - mkdir bin
  - go build -o ./bin/docker-machine.exe ./cmd/machine.go

test_script:
#  - go test -v ./...
  # test this from a PowerShell
  - ps: go test -v ./libmachine/shell
  - go vet ./...
  - git rev-parse HEAD
  # would be great if this would work to test both shells:
  - .\bin\docker-machine.exe create -d none --url http://1.2.3.4:2375 test
  - .\bin\docker-machine.exe env test
  - ps: .\bin\docker-machine.exe env test
deploy: off
